// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SituationDatabase;

namespace SituationDatabase.Migrations
{
    [DbContext(typeof(SituationContext))]
    [Migration("20200512145403_add-metatables")]
    partial class addmetatables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SituationDatabase.Models.Highlights.EffectiveHeGrenade", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("EnemiesHit")
                        .HasColumnType("int");

                    b.Property<int>("EnemiesKilled")
                        .HasColumnType("int");

                    b.Property<short>("Round")
                        .HasColumnType("smallint");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<long>("SteamId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalEnemyDamage")
                        .HasColumnType("int");

                    b.Property<int>("TotalTeamDamage")
                        .HasColumnType("int");

                    b.HasKey("MatchId", "Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("SteamId");

                    b.ToTable("EffectiveHeGrenade");
                });

            modelBuilder.Entity("SituationDatabase.Models.MatchEntity", b =>
                {
                    b.Property<long>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<float?>("AvgRank")
                        .HasColumnType("float");

                    b.Property<short>("BombDefuses1")
                        .HasColumnType("smallint");

                    b.Property<short>("BombDefuses2")
                        .HasColumnType("smallint");

                    b.Property<short>("BombExplodes1")
                        .HasColumnType("smallint");

                    b.Property<short>("BombExplodes2")
                        .HasColumnType("smallint");

                    b.Property<short>("BombPlants1")
                        .HasColumnType("smallint");

                    b.Property<short>("BombPlants2")
                        .HasColumnType("smallint");

                    b.Property<byte>("GameType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Map")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MoneyEarned1")
                        .HasColumnType("int");

                    b.Property<int>("MoneyEarned2")
                        .HasColumnType("int");

                    b.Property<int>("MoneySpent1")
                        .HasColumnType("int");

                    b.Property<int>("MoneySpent2")
                        .HasColumnType("int");

                    b.Property<short>("NumRoundsCt1")
                        .HasColumnType("smallint");

                    b.Property<short>("NumRoundsCt2")
                        .HasColumnType("smallint");

                    b.Property<short>("NumRoundsT1")
                        .HasColumnType("smallint");

                    b.Property<short>("NumRoundsT2")
                        .HasColumnType("smallint");

                    b.Property<short>("RealScore1")
                        .HasColumnType("smallint");

                    b.Property<short>("RealScore2")
                        .HasColumnType("smallint");

                    b.Property<short>("Score1")
                        .HasColumnType("smallint");

                    b.Property<short>("Score2")
                        .HasColumnType("smallint");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("WinnerTeam")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("MatchId");

                    b.HasIndex("MatchId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("SituationDatabase.Models.Misplays.SmokeFail", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("LineupId")
                        .HasColumnType("int");

                    b.Property<string>("LineupName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<short>("Round")
                        .HasColumnType("smallint");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<long>("SteamId")
                        .HasColumnType("bigint");

                    b.HasKey("MatchId", "Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("SteamId");

                    b.ToTable("SmokeFail");
                });

            modelBuilder.Entity("SituationDatabase.Models.PlayerMatchEntity", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("SteamId")
                        .HasColumnType("bigint");

                    b.Property<short>("AssistCount")
                        .HasColumnType("smallint");

                    b.Property<short>("DeathCount")
                        .HasColumnType("smallint");

                    b.Property<short>("KillCount")
                        .HasColumnType("smallint");

                    b.Property<short>("Mvps")
                        .HasColumnType("smallint");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<byte>("Team")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("MatchId", "SteamId");

                    b.HasIndex("MatchId");

                    b.ToTable("PlayerMatch");
                });

            modelBuilder.Entity("SituationDatabase.Models.PlayerRoundEntity", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<short>("RoundNumber")
                        .HasColumnType("smallint");

                    b.Property<long>("SteamId")
                        .HasColumnType("bigint");

                    b.Property<byte>("ArmorType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsCt")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MoneyInitial")
                        .HasColumnType("int");

                    b.Property<int>("PlayedEquipmentValue")
                        .HasColumnType("int");

                    b.HasKey("MatchId", "RoundNumber", "SteamId");

                    b.HasIndex("MatchId");

                    b.HasIndex("MatchId", "SteamId");

                    b.ToTable("PlayerRound");
                });

            modelBuilder.Entity("SituationDatabase.Models.RoundEntity", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<short>("Round")
                        .HasColumnType("smallint");

                    b.Property<bool>("BombPlanted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<bool>("OriginalSide")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("PlayerMatchMatchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlayerMatchSteamId")
                        .HasColumnType("bigint");

                    b.Property<int>("RealEndTime")
                        .HasColumnType("int");

                    b.Property<int>("RoundTime")
                        .HasColumnType("int");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<byte>("WinType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("WinnerTeam")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("MatchId", "Round");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerMatchMatchId", "PlayerMatchSteamId");

                    b.ToTable("Round");
                });

            modelBuilder.Entity("SituationDatabase.Models.PlayerMatchEntity", b =>
                {
                    b.HasOne("SituationDatabase.Models.MatchEntity", "Match")
                        .WithMany("PlayerMatch")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SituationDatabase.Models.PlayerRoundEntity", b =>
                {
                    b.HasOne("SituationDatabase.Models.MatchEntity", "Match")
                        .WithMany("PlayerRound")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SituationDatabase.Models.RoundEntity", "Round")
                        .WithMany("PlayerRound")
                        .HasForeignKey("MatchId", "RoundNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SituationDatabase.Models.PlayerMatchEntity", "PlayerMatch")
                        .WithMany("PlayerRound")
                        .HasForeignKey("MatchId", "SteamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SituationDatabase.Models.RoundEntity", b =>
                {
                    b.HasOne("SituationDatabase.Models.MatchEntity", "Match")
                        .WithMany("Round")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SituationDatabase.Models.PlayerMatchEntity", "PlayerMatch")
                        .WithMany("Round")
                        .HasForeignKey("PlayerMatchMatchId", "PlayerMatchSteamId");
                });
#pragma warning restore 612, 618
        }
    }
}
